version: '3.8'

services:
  nest-2024-postgres:
    image: postgres:17
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
      POSTGRES_DB: '${POSTGRES_DB:-nest-2024}'
    volumes:
      - ./nest-2024-api-db:/var/lib/postgresql/nest-2024

  nest-2024-redis:
    image: redis:7.0.15
    ports:
      - '${REDIS_PORT:-6379}:6379'

    restart: unless-stopped

  nest-2024-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "7800:9000"
      - "7801:9001"
    volumes:
      - ./nest-2024-api-s3-data:/usr/src/app/s3
    environment:
      - MINIO_ROOT_USER=user            # AWS_S3_ACCESS_KEY
      - MINIO_ROOT_PASSWORD=password    # AWS_S3_SECRET_KEY

volumes:
  nest-2024-api-db:
  nest-2024-api-s3: